name: Weekly Cuma Hutbe Email

on:
  schedule:
    # Runs every Friday at 9:00 AM UTC (adjust to your timezone)
    - cron: "30 9 * * 5"
  workflow_dispatch:  # Allow manual run

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pdf2image pillow

      - name: Run script
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
          TARGET_URL: ${{ secrets.TARGET_URL }}
        run: python cuma_hutpa.py
